### PR TITLE
Add csharp example created by Damien

### PR DESCRIPTION
**Pull request by jbaldassari**

### CODE REVIEW

**Review by damien-mabl — COMMENTED** [review]
Looks good overall, the only thing I might think to add is a small readme that suggests that dependency resolution will rely on using nuget -- but if you're running Visual Studio and coding automation in C# you probably already know that?   I'm not sure if it's worth mentioning -- it's equivalent to mentioning Mavencentral in java.

**Comment by kblok** [comment]
I just came to say: C# ❤️

**Comment by jbaldassari** [comment]
> only thing I might think to add is a small readme that suggests that dependency resolution will rely on using nuget

@damien-mabl maybe it would make sense to document the `nuget` commands as well.  If you want to propose something I can add it here.

**Comment by jbaldassari** [comment]
@kblok careful! next time we'll ask you :smile:

**Comment by kblok** [comment]
@jbaldassari glad to help!

**Pull request merged**
